---

title: PKDB
description: Personal Knowledge DatabBase
locale: en
email: alexbl1996@gmail.com
baseurl: /pkdb
url: https://blalop.github.io/pkdb/
social:
  github: blalop

# logo: ""
theme: jekyll-theme-persephone
theme_setting:
  blog_page: "index.md"
  about_page: "about.md"
  archive_page: "archive.md"
  nav_pages:
    - "about.md"
    - "archive.md"

plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - README.md
